server:
  port: 9002
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/ #eureak集群配置