server:
  port: 8999
spring:
  application:
    name: eureka-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  routes:
    user:
      path: /user-cluster/**
      serviceId: user-client
ribbon:
  eureka:
    enable: false
user-client:
  ribbon:
    listOfServers: http://localhost:9008,http://localhost:9009
