#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.103:53306/boot2
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    schema:
#      - classpath:department.sql #\u6307\u5B9A\u5EFA\u8868\u8BED\u53E5\u6587\u4EF6\u6216\u8005sql\u6267\u884C\u6587\u4EF6
#    type: com.alibaba.druid.pool.DruidDataSource
spring:
  profiles:
    active:
    - druid